export const ELATION_IDENTIFIER_SYSTEM = 'https://www.elationhealth.com/'
export const BREAST_CANCER_SCREENING_PATHWAY_DEFINITION_ID = '9yXrOSSR43f7'
export const LAST_BREAST_SCREENING_DATE_DATA_POINT_DEFINITION_ID = 'QbzLyxg6XQB9'